version: '3'

services:
  ghost:
    build:
      context: .
      dockerfile: ./ghost.Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      # Database connection
      database__client: postgres
      database__connection__host: db
      database__connection__user: ${POSTGRES_USER:-ghost}
      database__connection__password: ${POSTGRES_PASSWORD:-ghostpassword}
      database__connection__database: ${POSTGRES_DB:-ghost}
      
      # Ghost configuration
      url: ${GHOST_URL:-http://localhost:2368}
      NODE_ENV: ${NODE_ENV:-production}
      
      # Mail configuration
      mail__transport: SMTP
      mail__options__service: ${MAIL_SERVICE:-Mailgun}
      mail__options__host: ${MAIL_HOST:-smtp.mailgun.org}
      mail__options__port: ${MAIL_PORT:-587}
      mail__options__secureConnection: ${MAIL_SECURE:-false}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
      mail__from: ${MAIL_FROM:-'Ghost Blog <noreply@yourdomain.com>'}
    volumes:
      - ghost_content:/var/lib/ghost/content
    ports:
      - "${GHOST_PORT:-2368}:2368"
    networks:
      - ghost_network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ghost}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ghostpassword}
      POSTGRES_DB: ${POSTGRES_DB:-ghost}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ghost_network

volumes:
  ghost_content:
  postgres_data:

networks:
  ghost_network:
    driver: bridge